export const STAT_GROWTH = {
    Warrior: {
        str: 2,
        agi: 1,
        hp: 10,
        mp: 2,
        int: 0,
        wis: 0,
        dex: 1,
        lck: 0,
    },
    MindMage: {
        str: 0,
        agi: 1,
        hp: 5,
        mp: 10,
        int: 2,
        wis: 1,
        dex: 0,
        lck: 1,
    },
    ToothSage: {
        str: 1,
        agi: 1,
        hp: 6,
        mp: 5,
        int: 1,
        wis: 1,
        dex: 2,
        lck: 1,
    },
    Scholar: {
        str: 0,
        agi: 1,
        hp: 5,
        mp: 8,
        int: 2,
        wis: 2,
        dex: 1,
        lck: 1,
    },
    Sentinel: {
        str: 2,
        agi: 1,
        hp: 8,
        mp: 3,
        int: 0,
        wis: 1,
        dex: 2,
        lck: 1,
    },
    Forager: {
        str: 1,
        agi: 1,
        hp: 6,
        mp: 4,
        int: 1,
        wis: 1,
        dex: 2,
        lck: 2,
    },
    SpiritMonk: {
        str: 0,
        agi: 1,
        hp: 6,
        mp: 8,
        int: 2,
        wis: 2,
        dex: 0,
        lck: 2,
    },
    Merchant: {
        str: 1,
        agi: 1,
        hp: 6,
        mp: 4,
        int: 1,
        wis: 1,
        dex: 1,
        lck: 3,
    },
};
